/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "myprog.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = {25, 0};

bool_t *
register_client_1(client *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, register_client,
				  (xdrproc_t)xdr_client, (caddr_t)argp,
				  (xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
				  TIMEOUT) != RPC_SUCCESS)
	{
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
send_message_1(message *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, send_message,
				  (xdrproc_t)xdr_message, (caddr_t)argp,
				  (xdrproc_t)xdr_bool, (caddr_t)&clnt_res,
				  TIMEOUT) != RPC_SUCCESS)
	{
		return (NULL);
	}
	return (&clnt_res);
}

message *
fetch_message_1(client *argp, CLIENT *clnt)
{
	static message clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, fetch_message,
				  (xdrproc_t)xdr_client, (caddr_t)argp,
				  (xdrproc_t)xdr_message, (caddr_t)&clnt_res,
				  TIMEOUT) != RPC_SUCCESS)
	{
		return (NULL);
	}
	return (&clnt_res);
}
