/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "myprog.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h> // Add this header for inet_addr function

#ifndef SIG_PF
#define SIG_PF void (*)(int)
#endif

static void
myapp_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		client register_client_1_arg;
		message send_message_1_arg;
		client fetch_message_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case register_client:
		_xdr_argument = (xdrproc_t)xdr_client;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))register_client_1_svc;
		break;

	case send_message:
		_xdr_argument = (xdrproc_t)xdr_message;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))send_message_1_svc;
		break;

	case fetch_message:
		_xdr_argument = (xdrproc_t)xdr_client;
		_xdr_result = (xdrproc_t)xdr_message;
		local = (char *(*)(char *, struct svc_req *))fetch_message_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

int main(int argc, char **argv)
{
	char *ip_address;
	if (argc < 2)
	{
		ip_address = "127.0.0.1"; // Default to localhost
	}
	else
	{
		ip_address = argv[1];
	}

	struct sockaddr_in addr;
	addr.sin_family = AF_INET;
	addr.sin_addr.s_addr = inet_addr(ip_address);
	addr.sin_port = 0;

	register SVCXPRT *transp_udp, *transp_tcp;

	pmap_unset(MYAPP_PROG, MYAPP_VERSION);

	// Create and bind UDP service
	int udp_sock = socket(AF_INET, SOCK_DGRAM, 0);
	if (udp_sock < 0)
	{
		perror("socket");
		exit(1);
	}
	if (bind(udp_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0)
	{
		perror("bind");
		exit(1);
	}
	transp_udp = svcudp_create(udp_sock);
	if (transp_udp == NULL)
	{
		fprintf(stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp_udp, MYAPP_PROG, MYAPP_VERSION, myapp_prog_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (MYAPP_PROG, MYAPP_VERSION, udp).");
		exit(1);
	}

	// Create and bind TCP service
	int tcp_sock = socket(AF_INET, SOCK_STREAM, 0);
	if (tcp_sock < 0)
	{
		perror("socket");
		exit(1);
	}
	if (bind(tcp_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0)
	{
		perror("bind");
		exit(1);
	}
	if (listen(tcp_sock, SOMAXCONN) < 0)
	{
		perror("listen");
		exit(1);
	}
	transp_tcp = svctcp_create(tcp_sock, 0, 0);
	if (transp_tcp == NULL)
	{
		fprintf(stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp_tcp, MYAPP_PROG, MYAPP_VERSION, myapp_prog_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (MYAPP_PROG, MYAPP_VERSION, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "%s", "svc_run returned");
	exit(1);
	/* NOTREACHED */
}